version: "3"
networks:
  expense:
services:
  mysql:
    image: srlaf/mysql:v1
    container_name: mysql # --name mysql
    ports:
    - 3306:3306
  backend:
    image: srlaf/backend:v1
    container_name: backend
    ports:
    - 8080:8080
    command: sh -c "sleep 20 && node /opt/server/index.js"
    depends_on:
    - mysql
  frontend:
    image: srlaf/frontend:v1
    container_name: frontend
    ports:
    - 80:80
    depends_on:
    - backend